export PATH=/bin:/usr/bin:/usr/local/bin:${PATH}

export ZSH="$HOME/.oh-my-zsh"

export WORKON_HOME="$HOME/.virtualenvs"

ZSH_THEME="robbyrussell"

zet() {
  nvim "+Zet $*"
}

plugins=(git python nvm npm tmux vscode colorize docker jira)

source $ZSH/oh-my-zsh.sh

# User configuration
source $HOME/.aliases

export MANPATH="/usr/local/man:$MANPATH"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='mvim'
fi

# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
# Linking support by default
export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"

# Aliases
if [ -f ~/.aliases ]; then
  . ~/.aliases
fi

# FZF
export FZF_DEFAULT_COMMAND='rg --files --hidden'
export FZF_DEFAULT_OPTS='--bind ctrl-j:down,ctrl-k:up'

# NVM
export NVM_DIR="$HOME/.nvm"
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# GO
export PATH="$PATH:/usr/local/go/bin"
export GOBIN="$GOPATH/bin"
export GOPATH="$HOME/code/go_workspace"
export GOROOT="/usr/local/opt/go/libexec"
export PATH="$PATH:$GOPATH"
export PATH="$PATH:$GOBIN"

# PYENV
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

# BASE16
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

#####
export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
export PATH="$PATH:/Users/munsterberg/.local/bin"
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/share/npm/bin:$PATH"
export DYLD_LIBRARY_PATH=/usr/local/opt/openssl/lib:$DYLD_LIBRARY_PATH

eval "$(rbenv init -)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
